name: "Deploy"

on:
  release:
    types: [published]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: npm test

  deploy:
    name: Deploy to npm
    if: ${{ github.event_name == 'release' }}
    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: npm i
      - run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
